export const paths = {
  home: '',
  repertoire: 'repertoire',
  admin: 'admin',
  basket: 'basket',
  confirmation: 'confirmation',
  reservation: 'booking',
  summary: 'summary',
  myTickets: 'my-tickets',
  orders: 'orders',
  watchlist: 'watchlist',
  login: 'auth',
  logout: 'logout',
  notFound: '404',
} as const;
